### ISSUE TITLE
十分感谢作者，这边尝试本地部署了一份MisakiBot，在使用了几天有几点建议。

### ISSUE THREAD

**Issue by Oridzuru** [HkskKazeo/MisakiBot#2]
十分感谢作者，这边尝试本地部署了一份MisakiBot，在使用了几天有几点建议。

- 可能将dataupdate.py 中的方法解耦，以后调用会方便一些。

- 因为matsurihi.me接口有时候有一点点延迟，在18 or 48分时候未必有数据更新。可能可以考虑将cron模式换成interval模式 minute=5 or 10 左右。

- 同样因为matsurihi.me延迟，在18 or 48分时候未必有数据更新，导致数据延迟30分钟以上。可以把分离出来数据更新的function，用一个command 直接来触发请求更新数据。

- 更新的时间后面可以标注（日本时间） 或者将时间改成 +08:00 的北京时间。

**Comment by HkskKazeo** [comment]
感谢建议！这段时间一直加班没什么时间，刚看到...
关于解耦：你说得对，不知不觉就堆了这么多，再加上python我也算是初学代码习惯不好，有空会整理一下。
关于cron模式：matsuri更新时间不确定这个问题我是经过了几次活动才发现的。正在做和你说法类似的改写，不过鸽了几周了。
关于时间标注：我会测试下你pr里的输出格式（之前因为输出字数较多在移动端显示效果不好已经精简过）。北京时间不考虑（我感觉我群里海外党挺多的...日服游戏还是显示+9比较合适）
这些我应该会在过年期间处理，再次感谢你的建议
